asset_path: /home/hcis-s22/benyang/IsaacLab/URDF/spoon_franka/spoon_franka.urdf
usd_dir: /home/hcis-s22/benyang/IsaacLab/source/isaaclab_assets/data/franka
usd_file_name: spoon_franka
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: false
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: null
    damping: null
collider_type: convex_decomposition
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: true
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags:
- !!python/tuple
  - class
  - robot
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 5.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: 2000
  solver_velocity_iteration_count: 1000
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: null
  contact_offset: 1.0e-05
  rest_offset: 1.0e-05
  torsional_patch_radius: null
  min_torsional_patch_radius: null
activate_contact_sensors: false
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: true
  solver_position_iteration_count: 800
  solver_velocity_iteration_count: 0
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-04-29 at 14:50:21.
##
